export const NATIONALITIES = {
  AU: "AU",
  BR: "BR",
  CA: "CA",
  CH: "CH",
  DE: "DE",
  DK: "DK",
  ES: "ES",
  FI: "FI",
  FR: "FR",
  GB: "GB",
  IE: "IE",
  IR: "IR",
  NO: "NO",
  NL: "NL",
  NZ: "NZ",
  TR: "TR",
  US: "US",
};

export const NATIONALITIES_HUMAN_NAME = {
  [NATIONALITIES.AU]: ["Australian", "magenta"],
  [NATIONALITIES.BR]: ["Brazilian", "red"],
  [NATIONALITIES.CA]: ["Canadian", "#5B08CF"],
  [NATIONALITIES.CH]: ["Chinese", "orange"],
  [NATIONALITIES.DE]: ["German", "gold"],
  [NATIONALITIES.DK]: ["Danish", "lime"],
  [NATIONALITIES.ES]: ["Spanish", "green"],
  [NATIONALITIES.FI]: ["Finnish", "cyan"],
  [NATIONALITIES.FR]: ["French", "blue"],
  [NATIONALITIES.GB]: ["British", "geekblue"],
  [NATIONALITIES.IE]: ["Irish", "purple"],
  [NATIONALITIES.IR]: ["Iranian", "yellow"],
  [NATIONALITIES.NO]: ["Norwegian", "grey"],
  [NATIONALITIES.NL]: ["Dutch", "#193A44"],
  [NATIONALITIES.NZ]: ["New-Zealand", "#CCE694"],
  [NATIONALITIES.TR]: ["Turkish", "#95E82D"],
  [NATIONALITIES.US]: ["American", "#B0C227"],
};
